FROM n8nio/n8n:1.99.1

ENV N8N_HOST=0.0.0.0
ENV N8N_PORT=5678
ENV N8N_PROTOCOL=https
ENV PORT=5678
ENV WEBHOOK_URL=https://n8n-faceless.onrender.com/
ENV WEBHOOK_TUNNEL_URL=https://n8n-faceless.onrender.com/
ENV N8N_RUNNERS_ENABLED=true
ENV N8N_USER_MANAGEMENT_DISABLED=false
ENV N8N_DEFAULT_RUNNER_HOST=main
ENV N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
ENV DATABASE_URL=postgresql://n8ndb_gcea_user:i51r8M6tHFmN3GxSZR6iEnGThQ5D0GxV@dpg-d1fcieili9vc739t1jfg-a/n8ndb_gcea
ENV DB_POSTGRESDB_SSL_REJECT_UNAUTHORIZED=false
EXPOSE 5678