FROM n8nio/n8n:1.99.1

ENV N8N_HOST=0.0.0.0
ENV N8N_PORT=5678
ENV N8N_PROTOCOL=https
ENV PORT=5678
ENV WEBHOOK_URL=https://n8n-faceless.onrender.com/
ENV WEBHOOK_TUNNEL_URL=https://n8n-faceless.onrender.com/
ENV N8N_RUNNERS_ENABLED=true
ENV N8N_USER_MANAGEMENT_DISABLED=true
ENV N8N_DEFAULT_RUNNER_HOST=main
ENV N8N_BASIC_AUTH_ACTIVE=true
ENV N8N_BASIC_AUTH_USER=admin
ENV N8N_BASIC_AUTH_PASSWORD=n8n#passwd
ENV N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true

EXPOSE 5678