services:
  - type: web
    name: n8n-faceless
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    healthCheckPath: /healthz
    envVars:
      - key: PORT
        value: "5678"
      - key: N8N_PORT
        value: "5678"
      - key: N8N_HOST
        value: "0.0.0.0"
      - key: N8N_PROTOCOL
        value: "https"
      - key: WEBHOOK_TUNNEL_URL
        value: "https://n8n-faceless.onrender.com/"
      - key: WEBHOOK_URL
        value: "https://n8n-faceless.onrender.com/"
      - key: N8N_RUNNERS_ENABLED
        value: "true"
      - key: N8N_USER_MANAGEMENT_DISABLED
        value: "false"
      - key: N8N_DEFAULT_RUNNER_HOST
        value: "main"
      - key: N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS
        value: "true"
      - key: DATABASE_URL
        value: postgresql://n8ndb_gcea_user:i51r8M6tHFmN3GxSZR6iEnGThQ5D0GxV@dpg-d1fcieili9vc739t1jfg-a/n8ndb_gcea
      - key: DB_POSTGRESDB_SSL_REJECT_UNAUTHORIZED
        value: "false"